### ISSUE TITLE
Open the permissions of the features extracted from rescaled videos of ActivityNet-1.3

### ISSUE THREAD

**Issue by Minniemu** [UARK-AICV/VLTinT#11]
Hi,
Can you change  the permission on the Google Drive of the Agent feature to editing for user to download it, thanks!
Also, putting all of the features on the google drive maybe helpful of me(just a suggestion, thanks~

**Comment by Kashu7100** [comment]
Thank you for the request. But I don't think we need (or should) change to edit mode because it allows public people to remove it by accident. 
Please let me know if you are having trouble downloading the feature.

**Comment by Minniemu** [comment]
Hi 
I had encountered the following error message while using gdown to download the file, which I still can't access the file.
`
$gdown --fuzzy 'https://drive.google.com/file/d/1lOQG1FgDseRKDs3RNgpKd000OOZiag1s/view?usp=sharing'
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1lOQG1FgDseRKDs3RNgpKd000OOZiag1s `

**Comment by Kashu7100** [comment]
I am sorry. Could you try to manually download the file (without using `gdown`)?

**Comment by Kashu7100** [comment]
If you still have some trouble, please try the following OneDrive link:

https://uark-my.sharepoint.com/:u:/g/personal/khoavoho_uark_edu/Ed8zWn_4Y8xKtBEE1e8tnbQBA7rk8wx1PVxxylXGz2QBHw?e=Wep2gN
