### ISSUE TITLE
about YouCook2 dataset

### ISSUE THREAD

**Issue by myccver** [UARK-AICV/VLTinT#12]
Thank you for your excellent work!
Could you provide the original videos of the YouCook2 dataset? Some videos on YouTube are damaged and cannot be downloaded.

**Comment by Kashu7100** [comment]
Hello, 

I cannot directly provide you the data. But you can fill the official request form of YouCook2 dataset for the request regarding the missing data. You can find the form here: [https://forms.gle/RciAsErjQJKQxYss8](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.gle%2FRciAsErjQJKQxYss8&data=04%7C01%7Ckyamazak%40uark.edu%7C043c5f0d0b534857852b08d9ab77c1bb%7C79c742c4e61c4fa5be89a3cb566a80d1%7C0%7C0%7C637729353707033691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bw10qFKaSqvq2tu6I10wuL1aUZcP128A4SbJHMfhPe4%3D&reserved=0)
