### ISSUE TITLE
What should be placed inside the folder 'video_feature/anet_trainval'?

### ISSUE THREAD

**Issue by shaohuaJK** [UARK-AICV/VLTinT#15]
What should be placed inside the folder 'video_feature/anet_trainval'?
![1705051496260](https://github.com/UARK-AICV/VLTinT/assets/80374175/9d5d1024-769a-4792-a06f-325ed52ad42b)

**Comment by Kashu7100** [comment]
Thanks for your interest.

I don't think you need that directory.
