### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/video/dir'

### ISSUE THREAD

**Issue by tjumc** [UARK-AICV/VLTinT#4]
![image](https://user-images.githubusercontent.com/67730345/224033650-beac9650-be75-4999-a356-a94460581784.png)
I ran into some problems in preparatory work，how to solve this problem?

**Comment by Kashu7100** [comment]
Hi, thanks for your interests. 

Could you please replace the `path/to/video/dir` and `path/to/dir` in the following command to match with your environment?
```bash
python preprocess/convert_to_mp4.py --video-root path/to/video/dir --output-root path/to/dir/*.mp4
```
where
- `path/to/video/dir`is where you store the raw video of Anet or YC2 datasets.
- `path/to/dir` is your desired output directory.
