### ISSUE TITLE
share the captions generated by your model

### ISSUE THREAD

**Issue by wanghao14** [UARK-AICV/VLTinT#7]
Hi, thanks for sharing the wonderful work. Could you please share the caption results generated by your model (which should be `results/anet_re_*/greedy_pred_[val/test].json` mentioned in your README, and I also want the generated result of YouCookII) so I can compared the result with mine and make some visualization display. We will cite your work and hope to get your help. Thank you in advance.

**Comment by wanghao14** [comment]
@Kashu7100 Looking forward to your reply.

**Comment by Kashu7100** [comment]
Thank you for your inquiry. I am happy to help you. 
I need to search for my old drive for the generated results (and there are many) so it might take a while to get that file. 

I will find some time and I will get back to you later. 
If I don't reply in a week, please feel free to ping me again.

**Comment by wanghao14** [comment]
Thanks for you reply, but one week seems too long for me to give responses to my reviewers :(. If possible, could you please send all the generated results to my email （whscut@outlook.com） so that I can search for your best results.

**Comment by Kashu7100** [comment]
Please check your email. Closing this issue but feel free to reopen if you have further comments.

**Comment by EileenWang1996** [comment]
Hello, I'm also interested in the generated results from your model. Would you perhaps be able to share this with me too if possible?
